### ISSUE TITLE
Adding custom tokens to the dashboard: is there a cap of 2 tokens?

### ISSUE THREAD

**Issue by miltonwg** [rsksmart/rif-identity-manager#25]
Adding tokens in Ethereum:

- added DAI: Balance shown OK
- added CryptoKitties: OK
- added SAI: nothing happened --> is there a cap of 2 tokens?

**Comment by jessgusclark** [comment]
Hey @miltonwg, 

There is no limit to the number of coins you can have, but it does seem like there is an issue with the SAI coin.

![image](https://user-images.githubusercontent.com/766679/101476600-b2858e80-3956-11eb-95ea-09c27bf7e302.png)

Is this the address you are using for SAI? `0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359`

Error returned from the contract above, SAI, is: 

```
symbol [ethjs-contract] while formatting incoming raw call data "0x4441490000000000000000000000000000000000000000000000000000000000" Error: Number can only safely store up to 53 bits
tokens.ts:36 name [ethjs-contract] while formatting incoming raw call data "0x44616920537461626c65636f696e2076312e3000000000000000000000000000" Error: Number can only safely store up to 53 bits
```

**Comment by jessgusclark** [comment]
The SAI coin on the Ethereum network stores its name and symbol as a HEX. Here is the Symbol:
```
0x4441490000000000000000000000000000000000000000000000000000000000
```

Ideally, we could convert this to a string, however, the package we are using to fetch this information, `ethjs-contract`, tries to convert it to a number. This throws the error `Error: Number can only safely store up to 53 bits`. 

Further research into this shows that the contract address above for DAI/SAI is no longer valid. [See the warning on Etherscan](https://etherscan.io/address/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359). 

It looks like the updated address is `0x6B175474E89094C44Da98b954EedeAC495271d0F` and that works correctly with the Id Manager. 

Since no one will be using the older address, I'm going to close this ticket.
